version: "2"
services: 
  server:
    container_name: rorcalc_server
    restart: always
    build: ./server
    ports:
      - "2020:2020"
    depends_on:
      - mongo
  client: 
    container_name: rorcalc2_client
    restart: always
    build: ./rorcalc2
    ports:
      - "3000:3000"
    links: 
      - server
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
